version: "3.9"

services:
  api:
    environment:
      ENV: development
    volumes:
      - ./api:/app
      - ./sa.json:/secrets/sa.json:ro
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--reload-dir", "/app" ]

  frontend:
    volumes:
      - ./frontend:/usr/share/nginx/html:ro